# Generated by Django 4.2.1 on 2023-06-07 20:35

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blogindexpage_featured_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_car",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title",
                        wagtail.blocks.CharBlock(
                            help_text="Name of the featured car.",
                            required=True,
                        ),
                    ),
                    ("url", wagtail.blocks.CharBlock(required=True)),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(required=True),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
