# Generated by Django 4.2.1 on 2023-06-23 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_remove_categorypage_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_posts",
                to="blog.categorypage",
            ),
        ),
    ]
