# Generated by Django 4.2.1 on 2023-06-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0025_alter_carhubpage_reddit_posts"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedditEmbed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("subreddit", models.CharField(max_length=15)),
                ("last_updated", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="carhubpage",
            name="reddit_posts",
        ),
        migrations.AddField(
            model_name="carhubpage",
            name="reddit_embeds",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.redditembed",
            ),
        ),
    ]
