# Generated by Django 4.2.1 on 2023-06-07 21:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogindexpage_featured_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='featured_car',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True, use_json_field=True),
        ),
    ]
