# Generated by Django 4.2.1 on 2023-06-07 21:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogindexpage_featured_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='featured_car',
            field=wagtail.fields.StreamField([('person', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('surname', wagtail.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('biography', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
    ]
