# Generated by Django 4.2.1 on 2023-06-07 22:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogindexpage_featured_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='featured_car',
            field=wagtail.fields.StreamField([('Car', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], null=True, use_json_field=True),
        ),
    ]
