# Generated by Django 4.2.1 on 2023-06-07 22:57

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_blogindexpage_featured_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogindexpage",
            name="featured_cars",
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_car",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Car",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("url", wagtail.blocks.URLBlock()),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
