# Generated by Django 4.2.1 on 2023-06-08 01:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogindexpage_featured_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='featured_cars',
            field=wagtail.fields.StreamField([('Car', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=20)), ('description', wagtail.blocks.CharBlock(max_length=80)), ('url', wagtail.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], null=True, use_json_field=True),
        ),
    ]
