# Generated by Django 4.2.1 on 2023-06-09 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_blogpage_author_blogpage_body_blogpage_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='featured_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='snippet',
            field=models.CharField(help_text="Excerpt used in the article's preview card.", max_length=200),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='intro',
            field=wagtail.fields.RichTextField(),
        ),
    ]
