# Generated by Django 4.2.1 on 2023-06-11 01:24

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_alter_blogpage_author_alter_blogpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="category",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_posts",
                to="blog.categorypage",
            ),
            preserve_default=False,
        ),
    ]
