# Generated by Django 4.2.1 on 2023-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogpage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
