# Generated by Django 4.2.1 on 2023-06-15 06:54

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_categorypage_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='blog.categorypage'),
        ),
    ]
