# Generated by Django 4.2.1 on 2023-06-27 00:37

import apps.blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_carhubpage_reddit_embeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditembed',
            name='subreddit',
            field=models.CharField(max_length=15, validators=[apps.blog.validators.validate_subreddit_format, apps.blog.validators.validate_subreddit_exists]),
        ),
    ]
