# Generated by Django 4.2.1 on 2023-06-28 00:11

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0029_alter_redditembed_subreddit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redditembed",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="categorypage",
            name="youtube_embeds",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Youtube",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "youtube_link",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        max_height=350, max_width=520
                                    ),
                                ),
                                ("source_name", wagtail.blocks.CharBlock()),
                                ("source_url", wagtail.blocks.URLBlock()),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
