# Generated by Django 4.2.1 on 2023-06-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0030_remove_redditembed_last_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorypage",
            name="has_latest_post",
        ),
        migrations.AddField(
            model_name="categorypage",
            name="date_of_last_post",
            field=models.DateField(blank=True, default="2023-04-12"),
            preserve_default=False,
        ),
    ]
