# Generated by Django 4.2.4 on 2023-09-13 20:53

import apps.base.validators
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_carhubpage_resource_list_categorypage_resource_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='featured_cars',
            field=wagtail.fields.StreamField([('Car', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=20)), ('description', wagtail.blocks.CharBlock(max_length=80)), ('url', wagtail.blocks.URLBlock(label='Page URL')), ('image', wagtail.images.blocks.ImageChooserBlock())]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title')), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a Header size'), ('h2', 'H2'), ('h3', 'H3')], required=False))])), ('paragraph_block', wagtail.blocks.RichTextBlock(template='blocks/paragraph_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(max_length=100, required=False))])), ('quote_block', wagtail.blocks.StructBlock([('quote_text', wagtail.blocks.TextBlock()), ('attribute_name', wagtail.blocks.CharBlock(blank=True, required=False))], required=False)), ('youtube_embed_block', wagtail.blocks.StructBlock([('video', wagtail.blocks.URLBlock(help_text='Must be a YouTube embed URL.', validators=[apps.base.validators.validate_youtube_embed])), ('channel_name', wagtail.blocks.CharBlock()), ('channel_url', wagtail.blocks.URLBlock(help_text='e.g. https://www.youtube.com/@ChannelName', label='Channel URL', validators=[apps.base.validators.validate_youtube_channel]))], required=False))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='carhubpage',
            name='resource_list',
            field=wagtail.fields.StreamField([('resources', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=40)), ('urls', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock(help_text='External or internal URL.')), ('anchor', wagtail.blocks.CharBlock(label='Anchor text', max_length=40)), ('type', wagtail.blocks.ChoiceBlock(choices=[('TunerGuy', 'TunerGuy'), ('YouTube', 'YouTube'), ('Forums', 'Foruns'), ('Social', 'Social Media'), ('Article', 'Article'), ('Magazine', 'Magazine')]))])))], icon='clipboard-list'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='carhubpage',
            name='youtube_embeds',
            field=wagtail.fields.StreamField([('Youtube', wagtail.blocks.StructBlock([('video', wagtail.blocks.URLBlock(help_text='Must be a YouTube embed URL.', validators=[apps.base.validators.validate_youtube_embed])), ('channel_name', wagtail.blocks.CharBlock()), ('channel_url', wagtail.blocks.URLBlock(help_text='e.g. https://www.youtube.com/@ChannelName', label='Channel URL', validators=[apps.base.validators.validate_youtube_channel]))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='resource_list',
            field=wagtail.fields.StreamField([('resources', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=40)), ('urls', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock(help_text='External or internal URL.')), ('anchor', wagtail.blocks.CharBlock(label='Anchor text', max_length=40)), ('type', wagtail.blocks.ChoiceBlock(choices=[('TunerGuy', 'TunerGuy'), ('YouTube', 'YouTube'), ('Forums', 'Foruns'), ('Social', 'Social Media'), ('Article', 'Article'), ('Magazine', 'Magazine')]))])))], icon='clipboard-list'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='youtube_embeds',
            field=wagtail.fields.StreamField([('Youtube', wagtail.blocks.StructBlock([('video', wagtail.blocks.URLBlock(help_text='Must be a YouTube embed URL.', validators=[apps.base.validators.validate_youtube_embed])), ('channel_name', wagtail.blocks.CharBlock()), ('channel_url', wagtail.blocks.URLBlock(help_text='e.g. https://www.youtube.com/@ChannelName', label='Channel URL', validators=[apps.base.validators.validate_youtube_channel]))]))], null=True, use_json_field=True),
        ),
    ]
